spring:
  application:
    name: project-microservice
  datasource:
    url: jdbc:h2:file:~/proj
    username: sa
    password: password
server:
  port: 8004
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

