spring:
  application:
    name: task-microservice
  datasource:
    url: jdbc:h2:file:~/taskdb
server:
  port: 8003
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

